### ISSUE TITLE
打码的token能不能放到配置文件中去？

### ISSUE THREAD

**Issue by yriiolik** [coolxitech/AutoMihoyoBBS#1]
青龙面板里用起来方便一点。。

**Comment by CN-YoungYang** [comment]
你青龙 能正常运行么
![image](https://user-images.githubusercontent.com/25340441/198423420-a7c0cb62-aa93-4f5d-b156-07ac42cca1c4.png)
![image](https://user-images.githubusercontent.com/25340441/198423539-a33c4812-6682-40c8-9e02-b5e763c6e5b6.png)
