### ISSUE TITLE
刚自动获取的cookie马上失效

### ISSUE THREAD

**Issue by forchannot** [coolxitech/AutoMihoyoBBS#12]
![image](https://user-images.githubusercontent.com/100580891/200183579-96fdb231-a9a1-4dd6-aa36-63691fb43458.png)

**Comment by forchannot** [comment]
并且另一个号无法获取全部米游币，也没提示验证码，就在这一直循环
![image](https://user-images.githubusercontent.com/100580891/200183779-7b22cb14-96b7-4341-8b27-1e5c1abff623.png)

**Comment by forchannot** [comment]
实际上那个cookie并没过期，我用原版的可以跑

**Comment by anshifa958** [comment]
之前用的打码token在配置文件里的那版没问题，今天不知道咋回事报错了，更换了最新代码后auto_cookie开启的话会提示cookie过期，关闭的话会出现#10和#11的错误

**Comment by anshifa958** [comment]
auto_cookie可能还是有bug，然后我感觉报错可能是打码平台的服务器问题（猜测）

**Comment by coolxitech** [comment]
由于Cookie失效自动获取不太稳定已经回滚到定时执行写入Cookie的版本了

**Comment by CN-YoungYang** [comment]
出现 签到失败，你的cookie已过期, 这个报错。。  在 原版本是可以签到的, token也是填写了

**Comment by CN-YoungYang** [comment]
是在青龙里面跑的

**Comment by coolxitech** [comment]
> 是在青龙里面跑的

重新拉取代码

**Comment by CN-YoungYang** [comment]
这个是拉取配置

![image](https://user-images.githubusercontent.com/25340441/201029058-6de33813-d378-4db9-81ba-18177d5b03a2.png)

![image](https://user-images.githubusercontent.com/25340441/201029121-5b19c7a5-aa9f-4aa3-b592-92b4fa4fd301.png)


这个是打码配置
![image](https://user-images.githubusercontent.com/25340441/201028855-1c06f68e-873d-418d-8e7d-4f404e071e63.png)

这个是账号的设置
![image](https://user-images.githubusercontent.com/25340441/201029741-9fa3a47e-337a-4a1a-ab41-d64cacb38a93.png)

emmm，原来的属性没删，应该没影响吧
![image](https://user-images.githubusercontent.com/25340441/201029829-1d578bec-05ef-41af-a4ac-5e0de5437349.png)


运行以后
![image](https://user-images.githubusercontent.com/25340441/201030063-d7674a3d-008a-41d0-90c8-2713e65f00dc.png)

**Comment by CN-YoungYang** [comment]
然后 跑  Womsxd 的，就没有提示 cookie 过期
![image](https://user-images.githubusercontent.com/25340441/201031021-9fdbc804-acac-4130-aede-1ef3d74bca68.png)

**Comment by coolxitech** [comment]
> 然后 跑  Womsxd 的，就没有提示 cookie 过期
> ![image](https://user-images.githubusercontent.com/25340441/201031021-9fdbc804-acac-4130-aede-1ef3d74bca68.png)
> 

可以联系我qq6462175远程协助，青龙环境我也没调试过，我都是直接运行的脚本。

**Comment by coolxitech** [comment]
> 然后 跑 Womsxd 的，就没有提示 cookie 过期 ![image](https://user-images.githubusercontent.com/25340441/201031021-9fdbc804-acac-4130-aede-1ef3d74bca68.png)

建议在自己电脑跑一次

**Comment by forchannot** [comment]
> > 然后 跑 Womsxd 的，就没有提示 cookie 过期 ![image](https://user-images.githubusercontent.com/25340441/201031021-9fdbc804-acac-4130-aede-1ef3d74bca68.png)
> 
> 建议在自己电脑跑一次

打码网站登录不上，登录后就直接返回登录页，手机电脑都是如此，获取不了token

**Comment by coolxitech** [comment]
https://ocr.kuxi.tech/user/login?redirect=/user/login

**Comment by coolxitech** [comment]
> > > 然后 跑 Womsxd 的，就没有提示 cookie 过期 ![image](https://user-images.githubusercontent.com/25340441/201031021-9fdbc804-acac-4130-aede-1ef3d74bca68.png)
> > 
> > 
> > 建议在自己电脑跑一次
> 
> 打码网站登录不上，登录后就直接返回登录页，手机电脑都是如此，获取不了token

https://ocr.kuxi.tech/user/login?redirect=/user/login

**Comment by forchannot** [comment]
还是会这样，登录成功跳转后马上又回到这个页面
![image](https://user-images.githubusercontent.com/100580891/201069078-0e0e8131-5975-4859-961b-c38b64f7321e.png)

**Comment by coolxitech** [comment]
windows没出现过你这种问题，但是edge我也测过是正常能访问的.检查一下是否浏览器禁止存储缓存了，我代码里面写的没有登录缓存才会跳回登录界面.

**Comment by forchannot** [comment]
并没有设置啊，能正常存储缓存，手机上via和自带的小米浏览器也不行

**Comment by forchannot** [comment]
登录进去就会提示登录超时
![image](https://user-images.githubusercontent.com/100580891/201071741-4cd28170-d102-462e-a704-8b20b7b054fb.png)

**Comment by coolxitech** [comment]
可以QQ联系我提供一下账号

**Comment by forchannot** [comment]
> > 然后 跑 Womsxd 的，就没有提示 cookie 过期 ![image](https://user-images.githubusercontent.com/25340441/201031021-9fdbc804-acac-4130-aede-1ef3d74bca68.png)
> 
> 建议在自己电脑跑一次

电脑本地跑也会出现cookie失效，但是用原版跑还是没有失效

**Comment by forchannot** [comment]
![Screenshot_2022-11-11-10-05-42-393_com microsoft rdc androidx-edit](https://user-images.githubusercontent.com/100580891/201246621-e1006301-26f5-4de4-ba0d-15e9e19bfd53.jpg)
![Screenshot_2022-11-11-10-07-00-705_work master qinglongapp](https://user-images.githubusercontent.com/100580891/201246651-b2613b8d-4575-49f7-a2af-c7ef54dd50eb.jpg)

**Comment by forchannot** [comment]
好像确实可以了，再试几天确认下
