### ISSUE TITLE
关于模块报错问题

### ISSUE THREAD

**Issue by snacks-yummy** [coolxitech/AutoMihoyoBBS#15]
最近几天一直报错，貌似输入完后pip install -r requirements.txt    pip3 install -r requirements.txt -t    pip install PyYAML -t .
就一直报错图1，很奇怪然后发现系统装了Crypto 库 但是没什么印象是装了，本地运行是成功的然后上传云函数就报错Crypto 异常
我本地文件夹卸载Crypto就正常了

1：然后最疑惑的问题是我按照教程输入的为什么会安装Crypto库，不太明白

![1](https://user-images.githubusercontent.com/57312581/201559067-e36b7435-a291-4915-9c60-863c9794aca2.png)
![2](https://user-images.githubusercontent.com/57312581/201558821-72c696f3-fa03-49b7-90a5-f3ce7c9feb7e.png)
![3](https://user-images.githubusercontent.com/57312581/201558826-2252b1d0-c2c4-40e1-a351-3317ee976404.png)
![4](https://user-images.githubusercontent.com/57312581/201559083-387e3987-44c0-43f2-b9d5-83cb8a6d14aa.png)

**Comment by coolxitech** [comment]
建议看看requirements.txt的库名，代码里的crypto并不是使用的crypto库。
