### ISSUE TITLE
酷曦邀请码没办法正确跳转

### ISSUE THREAD

**Issue by FMercurYG** [coolxitech/AutoMihoyoBBS#16]
点了确定，没有调取qq
![image](https://user-images.githubusercontent.com/116616877/202945010-f33ff842-12e6-4c3a-9da8-bee60d18c99a.png)

**Comment by SouthernDreamS6** [comment]
> ![图片](https://user-images.githubusercontent.com/20185794/203117866-74846343-7919-4ea2-b33e-76015c855878.png) 不太清楚怎么会弹网页，我用edge点击是直接弹启动应用的框

+1
跳转没反应
获取到一个166开头的qq号在腾讯内搜不到

请问还有其他方法购买邀请码嘛

**Comment by coolxitech** [comment]
QQ6462175
