### ISSUE TITLE
配置好以后用docker启动直接报错

### ISSUE THREAD

**Issue by TohoKabo** [coolxitech/AutoMihoyoBBS#3]
![image](https://user-images.githubusercontent.com/112839899/198504664-176050ee-b205-4cd0-91e1-5e36bf782e45.png)

**Comment by CN-YoungYang** [comment]
需要装 装python库 。 库名是 pycryptodome

**Comment by TohoKabo** [comment]
> 需要装 装python库 。 库名是 pycryptodome

我安装的有这个库，还是报错

**Comment by coolxitech** [comment]
不好意思，我无法针对环境进行调试，基本没怎么整过docker容器

**Comment by TohoKabo** [comment]
前段时间用的好好的，换了打码平台之后就不行了

**Comment by coolxitech** [comment]
> 前段时间用的好好的，换了打码平台之后就不行了

最近是服务器出问题了，半夜才等到服务器修完了，已经加了台服务器当备用的了。
