### ISSUE TITLE
本地运行正常，阿里云函数报错

### ISSUE THREAD

**Issue by ronghc** [coolxitech/AutoMihoyoBBS#8]
大佬你好，我在使用过程中出现这如下报错，我在本地运行的时候是成功了，但是我在阿里云测试的时候报错了
{
    "errorMessage": "Module initialization error: 'Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-x86_64-linux-gnu.so', Not found '_raw_ecb.abi3.so', Not found '_raw_ecb.so''",
    "errorType": "UserCodeError",
    "stackTrace": [
        "OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-x86_64-linux-gnu.so'",
        "Not found '_raw_ecb.abi3.so'",
        "Not found '_raw_ecb.so'"
    ]
}
![image](https://user-images.githubusercontent.com/90175964/198874519-f96d84cd-898b-4dfa-b40a-08d2b1066bbf.png)

**Comment by anshifa958** [comment]
我用windows安装依赖后上传云函数报了错，后来换linux安装依赖后上传就好了
